QUERIES = {
    "master_data": "LOAD CSV WITH HEADERS FROM $path AS row FIELDTERMINATOR ';'"
    "MERGE (sub:Subject {name: row.Subject_ID, age: row.Age, sex: row.Sex, race: row.Race}) "
    "WITH sub, row CALL apoc.create.setProperty(sub, row.Visit_ID, row.Visit_number) YIELD node "
    "MERGE (site:Site {name: row.Sample_body_site}) "
    "MERGE (vis:Visit {visit_number:row.Visit_number, visit_id: row.Visit_ID}) "
    "MERGE (diag:Diagnosis {name:row.Diagnosis}) "
    "MERGE (sub)-[:VISIT]->(vis) "
    "MERGE (sub)-[:SAMPLED_AT]->(site) "
    "MERGE (sub)-[:DIAGNOSIS]->(diag)",
    "ecs": "LOAD CSV WITH HEADERS FROM $path AS line "
    "MATCH (vis:Visit)<-[:VISIT]-(sub:Subject) WHERE vis.visit_id = line.Visit_name "
    "FOREACH (genus IN (CASE WHEN line.Genus IS NOT NULL THEN [line.Genus] ELSE [] END) | "
    "MERGE (gen:Genus {name: genus}) "
    "MERGE (enz:Enzyme {name: line.Enzyme}) "
    "MERGE (enz)-[:EXPRESSED_BY "
    "{enzabs: line.Abundance_RPKs, visit_id: line.Visit_name, visit_number: vis.visit_number}]->(gen)) "
    "FOREACH (enzyme IN (CASE WHEN line.Genus IS NULL THEN [line.Enzyme] ELSE [] END) | "
    "MERGE (enz:Enzyme {name: enzyme}) "
    "MERGE (sub)-[:ENZ_ABS "
    "{enzabs: line.Abundance_RPKs, visit_id: line.Visit_name, visit_number: vis.visit_number}]->(enz)) ",
    "pwy": "LOAD CSV WITH HEADERS FROM $path AS line "
    "MATCH (vis:Visit)<-[:VISIT]-(sub:Subject) WHERE vis.visit_id = line.Visit_name "
    "FOREACH (genus IN (CASE WHEN line.Genus IS NOT NULL THEN [line.Genus] ELSE [] END) | "
    "MERGE (pwy:Pathway {name: line.PWY}) "
    "MERGE (gen:Genus {name: line.Genus}) "
    "MERGE (pwy)-[:EXPRESSED_BY "
    "{pwyabs: line.Abundance, visit_id: line.Visit_name, visit_number: vis.visit_number}]->(gen)) "
    "FOREACH(genus IN (CASE WHEN line.Genus IS NULL THEN [line.Genus] ELSE [] END) | "
    "MERGE (pwy:Pathway {name: line.PWY}) "
    "MERGE (sub)-[:PWY_ABS {pwyabs: "
    "line.Abundance, visit_id: line.Visit_name, visit_number: vis.visit_number}]->(pwy))",
    "tax": "LOAD CSV WITH HEADERS FROM $path AS line "
    "MATCH (vis:Visit)<-[:VISIT]-(sub:Subject) WHERE vis.visit_id = line.Visit_name "
    "WITH vis, sub, line WHERE NOT line.Genus IS NULL "
    "MERGE (gen:Genus {name: line.Genus}) "
    "MERGE (sub)-[:GENUS_ABS "
    "{genabs: line.Metaphlan2_Analysis, visit_id: line.Visit_name, visit_number: vis.visit_number}]->(gen)",
}
